### ISSUE TITLE
Wrong model-behaviour of exported fmu

### ISSUE THREAD

**Issue by Elfangor93** [creative-connections/Bodylight.js-OM-Compiler#4]
The fmu which I exported by using OM Compiler behaves not the same way as the original mo-file does:
![grafik](https://user-images.githubusercontent.com/39154009/55561570-a9104180-56f2-11e9-9ea3-5281c343b628.png)
(original mo-File)

![grafik](https://user-images.githubusercontent.com/39154009/55561613-bd543e80-56f2-11e9-9c5c-bf034c2352f1.png)
(fmu exported with OM Compiler)
I executed the fmu with FMPy on a linux machine...

I have the feeling, that the difference comes from the solver used in the exported FMUs of OpenModelica. I found something in the OM Ticket-System to that topic:
[https://trac.openmodelica.org/OpenModelica/ticket/4273](https://trac.openmodelica.org/OpenModelica/ticket/4273) 

I tried the euler solver directly in OMEdit, but I cant reproduce the horrible results of the fmu
![grafik](https://user-images.githubusercontent.com/39154009/55562195-bf6acd00-56f3-11e9-8a2a-46943a257932.png)
(euler solver in OMEdit)

Do you have any further ideas, where the difference is produced?
Do you see any possibilities to improve the behaviour of the fmu-files?

[BouncingBall.zip](https://github.com/creative-connections/Bodylight.js-OM-Compiler/files/3043777/BouncingBall.zip)

**Comment by david-polak** [comment]
Yes this is a known upstream issue. It is possible to configure the euler solver to work correctly for some models, but it is extremely sensitive to variation in step length and tolerance.
![Screenshot_20190404_170117](https://user-images.githubusercontent.com/5686338/55566111-525b3580-56fb-11e9-8027-ee3a62cc53cf.png)

It is also possible that the solver included in the FMU is not exactly the same as the solver in omc, it has been a while since I investigated the issue and I can't recall if they are kept in sync.

There is nothing we can do until the upstream OpenModelica team fixes the issue and allows for export of other solvers, until then I recommend using Dymola for the export.

**Comment by Elfangor93** [comment]
How can I force OM Copiler to use the correct tolerance and interval? As far as I see is the tolerance and interval in the fmu the default values independently of the settings in the mo-file...
How do you adjust that values to get nice results in the composer?

**Comment by david-polak** [comment]
Tolerance and step size is defined when the FMU is instantiated and stepped.

In OMEdit you can tune simulation parameters.

In the Composer you can set up model configuration by selecting the model in the left tree and configuring it in the right panel.
